### ISSUE TITLE
You literally copy and pasted a whole repository

### ISSUE THREAD

**Issue by Anticheater23** [Thing3487/Thing3487#1]
You seem to be angry at me because i used a few bits of code from Minecraft2's blooket cheats even though it appears you have copied a WHOLE repository of blooket hacks and put it on your page as if its yours so if you would like to continue this meaningless argument feel free but i will make sure you don't interfere with my work any longer. Good day

**Comment by Thing3487** [comment]
Sry, i didn't see the code right, it just saw the license

**Comment by Thing3487** [comment]
And i didn't steal

**Comment by Thing3487** [comment]
My website literally leads to his repo

**Comment by Thing3487** [comment]
> You seem to be angry at me because i used a few bits of code from Minecraft2's blooket cheats even though it appears you have copied a WHOLE repository of blooket hacks and put it on your page as if its yours so if you would like to continue this meaningless argument feel free but i will make sure you don't interfere with my work any longer. Good day



> You seem to be angry at me because i used a few bits of code from Minecraft2's blooket cheats even though it appears you have copied a WHOLE repository of blooket hacks and put it on your page as if its yours so if you would like to continue this meaningless argument feel free but i will make sure you don't interfere with my work any longer. Good day

Thats whats called forking

**Comment by Thing3487** [comment]
Only coderrs will know

**Comment by Thing3487** [comment]
forking  is for contributing

**Comment by Thing3487** [comment]
Just ask minesraft2
