### ISSUE TITLE
Minecraft2s blooket hacks are gone your welcome

### ISSUE THREAD

**Issue by Anticheater23** [Thing3487/Thing3487#2]

**Comment by Thing3487** [comment]
Fuck you

**Comment by Thing3487** [comment]
> No description provided.

https://github.com/Minesraft2/Blooket-Cheats

**Comment by Anticheater23** [comment]
That's not very appropriate language only people who have past elementary school would know.

**Comment by Thing3487** [comment]
> That's not very appropriate language only people who have past elementary school would know.

Some underage people  would take that as inappropriate language.  And stop changing the topic

**Comment by Anticheater23** [comment]
Womp Womp

**Comment by Thing3487** [comment]
Stop changing  the fucking topic fool, no,  or should i say _coder_
